#!/usr/bin/env python3
"""
Render the translated Alice in Wonderland into a Typst interlinear book.

Reads data/processed/alice_translated.jsonl and emits book/alice.typ:
  - title page
  - one chapter opener per "CHAPTER X." heading in the source
  - interlinear paragraphs (English line above, Bliss line beneath)

Bliss line: only content tokens that resolved to a real Unicode glyph are
emitted (placeholders like "[bci_id]" are skipped); punctuation passes
through. Function words are dropped (they are realised by Bliss grammatical
indicators, not standalone glyphs).

The BlissaryFont OTFs are copied from the sibling BlissFont repo into
book/fonts/ so the document is self-contained. Override the source with the
BLISSFONT_DIR environment variable.
"""
import json
import os
import re
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
PROC_DIR = os.path.abspath(os.path.join(HERE, "..", "data", "processed"))
TRANSLATED_PATH = os.path.join(PROC_DIR, "alice_translated.jsonl")
BOOK_DIR = os.path.abspath(os.path.join(HERE, "..", "book"))
FONT_DIR = os.path.join(BOOK_DIR, "fonts")
OUT_PATH = os.path.join(BOOK_DIR, "alice.typ")

CHAPTER_RE = re.compile(r"^CHAPTER\s+([IVXLC]+)\.?$")
FONT_FILES = ["BlissaryFont-Regular.otf", "BlissaryFont-SemiBold.otf", "BlissaryFont-Bold.otf"]


def parse_chapter(text: str) -> tuple[str, str] | None:
    """
    Return (roman_numeral, title) if `text` opens a chapter, else None.
    Handles both forms found in the Gutenberg source:
      "CHAPTER I.\nDown the Rabbit-Hole"   (merged into one paragraph)
      "CHAPTER I."                          (title in the next paragraph)
    """
    lines = [ln.strip() for ln in text.strip().split("\n") if ln.strip()]
    if not lines:
        return None
    m = CHAPTER_RE.match(lines[0])
    if not m:
        return None
    num = m.group(1)
    title = lines[1] if len(lines) > 1 else ""
    return num, title


def find_blissfont_dir() -> str | None:
    env = os.environ.get("BLISSFONT_DIR")
    if env and os.path.isdir(env):
        return env
    sibling = os.path.abspath(os.path.join(HERE, "..", "..", "BlissFont"))
    return sibling if os.path.isdir(sibling) else None


def stage_fonts() -> str:
    """Copy BlissaryFont OTFs into book/fonts/; return the font-family note."""
    bf = find_blissfont_dir()
    os.makedirs(FONT_DIR, exist_ok=True)
    if not bf:
        print("WARNING: BlissFont dir not found; fonts not staged. "
              "Set BLISSFONT_DIR or pass --font-path to typst.")
        return ""
    src = os.path.join(bf, "data", "processed")
    for fn in FONT_FILES:
        s = os.path.join(src, fn)
        if os.path.exists(s):
            shutil.copy2(s, os.path.join(FONT_DIR, fn))
    return bf


def esc_typst(s: str) -> str:
    """Escape a Typst string literal (both English and Bliss content)."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def bliss_line(sentences: list) -> str:
    """
    Build the Bliss glyph string for a paragraph from its sentences.

    Only content tokens that resolved to a real Unicode glyph (or a
    derivation composite) are emitted, separated by Bliss word spaces.
    Function words and ASCII punctuation are dropped — Bliss uses its own
    punctuation glyphs (exclamation_mark 8483, question_mark 8485, ...) which
    the pipeline does not yet emit, and ASCII punctuation would break the
    Typst string literal.
    """
    out: list[str] = []
    for sent in sentences:
        for tok in sent["translation"]:
            uni = tok.get("unicode", "")
            role = tok.get("role", "content")
            if role == "content" and uni and not uni.startswith("["):
                out.append(uni + " ")           # real glyph + Bliss word space
    return "".join(out).strip()


def iter_paragraphs(path: str):
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            yield json.loads(line)


def main() -> None:
    if not os.path.exists(TRANSLATED_PATH):
        raise SystemExit(f"Missing {TRANSLATED_PATH}. Run translate.py first.")
    bf = stage_fonts()
    os.makedirs(BOOK_DIR, exist_ok=True)

    parts: list[str] = [
        '// Auto-generated by scripts/render_book.py — do not edit by hand.',
        '#import "template.typ": title-page, chapter, para',
        '',
        '#set page(',
        '  paper: "a5",',
        '  margin: (top: 2.0cm, bottom: 2.0cm, inside: 1.6cm, outside: 1.6cm),',
        '  header: none,',
        '  footer: context align(center)[#text(8pt, gray.darken(20%))[#counter(page).display("I")]],',
        ')',
        '#set par(leading: 0.75em, justify: false)',
        '',
        '#title-page',
        '',
    ]

    paras = list(iter_paragraphs(TRANSLATED_PATH))
    i = 0
    n_chapters = 0
    n_paragraphs = 0
    while i < len(paras):
        p = paras[i]
        ch = parse_chapter(p["text"])
        if ch:
            num, title = ch
            # If the title wasn't on the same line, take it from the next para.
            if not title and i + 1 < len(paras):
                title = paras[i + 1]["text"].strip()
                i += 2
            else:
                i += 1
            parts.append(f'#chapter("{esc_typst(num)}", "{esc_typst(title)}")')
            n_chapters += 1
            continue
        bliss = bliss_line(p.get("sentences", []))
        # Only emit a paragraph block if it produced any Bliss glyphs,
        # so the book isn't littered with empty English-only lines.
        if bliss:
            parts.append(f'#para("{esc_typst(p["text"])}", "{esc_typst(bliss)}")')
            n_paragraphs += 1
        i += 1

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")

    print(f"Wrote {OUT_PATH}")
    print(f"  chapters: {n_chapters} | rendered paragraphs: {n_paragraphs} "
          f"(of {len(paras)} source)")
    if bf:
        print(f"  fonts staged from {bf} -> {FONT_DIR}")
    print("\nRender with:")
    print(f"  typst compile --font-path {FONT_DIR} {OUT_PATH} {os.path.join(BOOK_DIR, 'alice.pdf')}")


if __name__ == "__main__":
    main()
